# Generated by Django 6.0.1 on 2026-01-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FEClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hp", models.IntegerField()),
                ("strength", models.IntegerField()),
                ("magic", models.IntegerField()),
                ("skill", models.IntegerField()),
                ("speed", models.IntegerField()),
                ("luck", models.IntegerField()),
                ("defense", models.IntegerField()),
                ("resistance", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("level_cap", models.IntegerField(default=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("base_hp", models.IntegerField()),
                ("base_strength", models.IntegerField()),
                ("base_magic", models.IntegerField()),
                ("base_skill", models.IntegerField()),
                ("base_speed", models.IntegerField()),
                ("base_luck", models.IntegerField()),
                ("base_defense", models.IntegerField()),
                ("base_resistance", models.IntegerField()),
                ("growth_hp", models.IntegerField()),
                ("growth_strength", models.IntegerField()),
                ("growth_magic", models.IntegerField()),
                ("growth_skill", models.IntegerField()),
                ("growth_speed", models.IntegerField()),
                ("growth_luck", models.IntegerField()),
                ("growth_defense", models.IntegerField()),
                ("growth_resistance", models.IntegerField()),
                (
                    "base_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fe_data.feclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromotionBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hp", models.IntegerField()),
                ("strength", models.IntegerField()),
                ("magic", models.IntegerField()),
                ("skill", models.IntegerField()),
                ("speed", models.IntegerField()),
                ("luck", models.IntegerField()),
                ("defense", models.IntegerField()),
                ("resistance", models.IntegerField()),
                (
                    "from_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotes_from",
                        to="fe_data.feclass",
                    ),
                ),
                (
                    "to_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotes_to",
                        to="fe_data.feclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
