# Generated by Django 6.0.1 on 2026-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fe_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feclass",
            name="promoted",
            field=models.BooleanField(default=False),
        ),
    ]
