# Generated by Django 6.0.1 on 2026-02-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe_data', '0002_feclass_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='base_level',
            field=models.IntegerField(default=1),
        ),
    ]
