# Generated by Django 6.0.6 on 2026-08-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe_data', '0004_alter_character_growth_defense_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['recruitment_order']},
        ),
        migrations.AddField(
            model_name='character',
            name='can_promote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='character',
            name='recruitment_order',
            field=models.IntegerField(default=0),
        ),
    ]
